language: python
python:
  - 3.5
  - 3.6

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements.dev.txt"

script:
  - nosetests --with-coverage --cover-package=stegano

after_success:
  - coveralls
