language: python
python:
  - 3.6

env:
 - PIPENV_VENV_IN_PROJECT=1

install:
  - "pip install pipenv"
  - "pipenv install"
  - "pipenv install --dev"

script:
  # Run the test suit
  - nosetests --with-coverage --cover-package=stegano
  # Run the type checker
  - python tools/run_mypy.py

after_success:
  - coveralls
