language: python
python:
  - 3.5
  - 3.6

install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements.dev.txt"

script:
  # Run the test suit
  - nosetests --with-coverage --cover-package=stegano
  # Run the type checker
  - python tools/run_mypy.py

after_success:
  - coveralls
